version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html/src
      - ./public:/var/www/html/public
      - ./templates:/var/www/html/templates
    environment:
      - PHP_ERROR_REPORTING=E_ALL
      - BASE_URL=http://localhost:8080/

volumes:
  app-data: