[package]
name = "gosub_taffy"
version = "0.1.0"
edition = "2021"

[dependencies]
gosub_shared = { path = "../gosub_shared" }
gosub_render_backend = { path = "../gosub_render_backend" }
gosub_styling = { path = "../gosub_styling" }
gosub_typeface = { path = "../gosub_typeface" }
taffy = "0.5.2"
anyhow = "1.0.87"
regex = "1.10.5"
parley = { git = "https://github.com/linebender/parley", rev = "14070d5" }
log = "0.4.22"
