[package]
name = "gosub_styling"
version = "0.1.0"
edition = "2021"
authors = ["Gosub Community <info@gosub.io>"]
license = "MIT"

[dependencies]
gosub_shared = { path = "../gosub_shared" }
gosub_css3 = { path = "../gosub_css3" }
gosub_html5 = { path = "../gosub_html5" }
gosub_render_backend = { path = "../gosub_render_backend" }
gosub_typeface = { path = "../gosub_typeface" }
lazy_static = "1.5"
anyhow = "1.0.87"
regex = "1.10.6"
colors-transform = "0.2.11"
backtrace = "0.3.71"
log = "0.4.21"
rand = "0.9.0-alpha.1"

#[target.'cfg(target_arch = "wasm32")'.dependencies]
#web-sys = { version = "0.3.69", features = ["fontface"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
rust-fontconfig = "0.1.7"
itertools = "0.13.0"
serde = { version = "1.0.209", features = ["derive"] }
serde_json = "1.0.128"
memoize = "0.4.2"
thiserror = "1.0.58"
nom = "7.1.3"
