[package]
name = "gosub_svg"
version = "0.1.0"
edition = "2021"

[dependencies]
tiny-skia = "0.11.4"
gosub_shared = { path = "../gosub_shared" }
gosub_html5 = { path = "../gosub_html5" }
gosub_render_backend = { path = "../gosub_render_backend" }
resvg = { version = "0.43.0", optional = true }
anyhow = "1.0.87"



[features]
resvg = ["dep:resvg"]
