[package]
name = "gosub_net"
version = "0.1.0"
edition = "2021"
authors = ["Gosub Community <info@gosub.io>"]
license = "MIT"

[dependencies]
gosub_shared = { path = "../gosub_shared", features = [] }
gosub_config = { path = "../gosub_config", features = [] }
derive_more = { version = "1", features = ["from"] }
thiserror = "1.0.61"
ureq = "2.10.1"
anyhow = "1.0.87"
log = "0.4.22"
domain-lookup-tree = "0.1"
hickory-resolver = "0.24.1"
simple_logger = "5.0.0"
cookie = { version = "0.18.1", features = ["secure", "private"] }
http = "1.0.0"
url = "2.5.2"
