name: Bencher.dev benchmarks (baseline)

on:
  push:
    branches:
      - main

jobs:
  benchmark_base_branch:
    name: Continuous Benchmarking with Bencher
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: bencherdev/bencher@main
      - name: Track base branch benchmarks with Bencher
        run: |
          bencher run \
          --project gosub-engine \
          --token '${{ secrets.BENCHER_API_TOKEN }}' \
          --branch main \
          --testbed github-action-ci \
          --adapter rust \
          --err \
          --github-actions '${{ secrets.GITHUB_TOKEN }}' \
          cargo bench --all